name: qc-bench

dependencies:
    - base >= 4.7 && < 5
    - bench-lib
    - QuickCheck
    - smallcheck
    - leancheck
    - generic-random

library:
    source-dirs: src

executables:
    qc-bench:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - qc-bench
